# Generated by Django 2.2.6 on 2019-11-26 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ouvidoria', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={},
        ),
        migrations.AlterModelOptions(
            name='denuncias',
            options={},
        ),
        migrations.AlterModelOptions(
            name='elogios',
            options={},
        ),
        migrations.AlterModelOptions(
            name='funcionario',
            options={},
        ),
        migrations.AlterModelOptions(
            name='funcionariotelefone',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ouvidoria',
            options={},
        ),
        migrations.AlterModelOptions(
            name='reclamacoes',
            options={},
        ),
        migrations.AlterModelOptions(
            name='relatorio',
            options={},
        ),
        migrations.AlterModelOptions(
            name='relatoriofuncionario',
            options={},
        ),
        migrations.AlterModelOptions(
            name='relatorioouvidoria',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sugestoes',
            options={},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
    ]
